[package]
name = "copix"
version = "0.1.0"
authors = ["Elton <eltonp3103@gmail.com>"]
edition = "2018"

[dependencies]
tokio-tungstenite = "0.10.1"
futures = "0.3.5"
tokio = { version = "0.2", features = ["full"] }
